BOZENA_STATE_CZ = "sensor.bozena_stav"
BOZENA_STATE_DETAIL = "sensor.bozena_mower_state_detail"
BOZENA_MOWER_POSITION = "sensor.bozena_mower_position"
BOZENA_STATE = "sensor.bozena_mower_state"
BOZENA_DOMA = "binary_sensor.bozena_doma"
BOZENO_DOMU = "input_boolean.bozeno_domu"
BOZENO_SEKAT = "input_boolean.bozeno_sekat"
BOZENO_PAUZA = "input_boolean.bozeno_pauza"
BOZENA_ZAKAZ_SEKANI = "input_boolean.bozena_zakaz_sekani"
SWITCH_ALTAN_SVETLO = "switch.altan_svetlo"
SWITCH_CERPADLO_STUDNA = "switch.cerpadlo"
IB_CERPADLO_STUDNA = "input_boolean.cerpadlo"
SENSOR_SKLENIK_A = "binary_sensor.sklenik_a"
CASOVAC_CERPADLO_20 = "input_boolean.casovac_cerpadlo_20"
CERPADLO_BEH_MAX = "input_number.cerpadlo_beh_max"
INFO_CERPADLO_STUDNA = "switch.info_cerpadlo"
CERPADLO_PROUD = "sensor.cerpadlo_current"
CERPADLO_OK = "input_boolean.cerpadlo_ok"
IB_POSTRIK_U_VCHODU = "input_boolean.postrik_u_vchodu"
IB_POSTRIK_JAHODY = "input_boolean.postrik_jahody"
IB_POSTRIK_BREH = "input_boolean.postrik_breh"
IB_POSTRIK_SAD = "input_boolean.postrik_sad"
IB_BOZENA_UPDATE = "input_boolean.bozena_update"

SWITCH_POSTRIK_U_DOMU = "switch.67437207f4cfa25c69bc"
SWITCH_POSTRIK_DUM_VPRAVO = "switch.67437207f4cfa25c699a"

IB_POSTRIK_U_DOMU = "input_boolean.postrik_u_domu"

SCENE_POSTRIK_ON_U_VCHODU = "scene.lcpx0zryrrenoclq"
SCENE_POSTRIK_OFF_U_VCHODU = "scene.cettrwwaujr8pdmz"

SCENE_POSTRIK_ON_JAHODY = "scene.e7vtwjmv0khfotjf"
SCENE_POSTRIK_OFF_JAHODY = "scene.1ikqh89kabakovky"

SCENE_POSTRIK_ON_BREH = "scene.mhf3szpkxpkftx0b"
SCENE_POSTRIK_OFF_BREH = "scene.mmagkoas974hwahh"

SCENE_POSTRIK_ON_SAD = "scene.hi27qblhcehrvfok"
SCENE_POSTRIK_OFF_SAD = " scene.ojpda21sjy5vflfz"

MOWER_MAP = "input_text.mower_map"
MOWER_X = "input_number.bozena_x"
MOWER_Y = "input_number.bozena_y"

MAP_0_X = "input_number.indego_0_x"
MAP_0_Y = "input_number.indego_0_y"
MAP_1_X = "input_number.indego_1_x"
MAP_1_Y = "input_number.indego_1_y"
